### ISSUE TITLE
Change viewPlane to return a Plane3d, not a SketchPlane3d

### ISSUE THREAD

**Issue by ianmackenzie** [opensolid/webgl#2]
Instead of projecting directly into a `SketchPlane3d`, projection should really be done using the various `toScreenSpace` functions so that both perspective and orthographic cameras are handled properly. It would likely be more useful for `viewPlane` to return a `Plane3d` with the normal direction equal to `viewDirection`, to allow for code like

```
pointDepth =
    point |> Point3d.signedDistanceFrom (Camera3d.viewPlane camera)
```

which would be useful for checking if a given 3D point is (for example) between a near and a far clip plane.

**Comment by MartinSStewart** [comment]
If `Plane3d` is used, will the up direction of the plane match the camera's? As I understand it, for `Plane3d` the up direction is arbitrary and for `SketchPlane3d` it's explicit.

**Comment by ianmackenzie** [comment]
What do you mean the "up" direction of a `Plane3d`? A `Plane3d` is really just a point and a normal vector; a `SketchPlane3d` is a point plus X and Y basis directions.

This means that converting from a `SketchPlane3d` to a `Plane3d` is well defined/unambiguous (the plane normal is the cross product of the two sketch plane basis directions) but converting from a `Plane3d` to a `SketchPlane3d` means that the X and Y basis directions will end up being chosen arbitrarily.

So I guess you could say that the up direction is arbitrary in that if `Camera3d.viewPlane` returned a `Plane3d` and you then used `SketchPlane3d.fromPlane` to convert that to a `SketchPlane3d`, the X and Y directions of the returned sketch plane would be arbitrary (would probably not match the right and up directions of the camera). Is that what you mean?

**Comment by MartinSStewart** [comment]
> the X and Y directions of the returned sketch plane would be arbitrary (would probably not match the right and up directions of the camera). Is that what you mean?

Correct. I have code that relies on the X and Y directions being chosen in a consistent way (which I assumed in this context meant the sketch plane's Y axis matched the up direction of the camera).

**Comment by ianmackenzie** [comment]
One possibility would be to have both `Camera3d.viewPlane` and `Camera3d.viewSketchPlane` (or maybe just `Camera3d.sketchPlane`), but then it would be weird if the normal of the plane wasn't consistent with the X and Y directions of the sketch plane. What do you think would make most sense as the normal direction of a camera's view plane?

  - Out of the screen:
    - Consistent with the sketch plane
    - Kinda makes sense as "outwards normal direction of the physical monitor screen"
  - Into the screen:
    - Seems more useful for checking distance of objects from the view plane, since positive would mean visible and negative would mean hidden/clipped

Can you also describe a bit more what you're using the sketch plane for? I kinda figured most use cases of "project into sketch plane" would be handled by the explicit `toScreenSpace` functions...it could be that there are some other similar functions that should be added.

**Comment by MartinSStewart** [comment]
> Can you also describe a bit more what you're using the sketch plane for?

I'm using the sketch plane in this game https://martinsstewart.gitlab.io/surface-voyage/ for when the user clicks on the screen. Their click position is projected onto a sketch plane 2 meters from the camera* and the distance between that projected position and the center of the screen (also projected onto the sketch plane) is used to determine how long the character should walk in a given direction. If the X and Y of the sketch plane were to change then the character will walk in the wrong direction.

> What do you think would make most sense as the normal direction of a camera's view plane?

Not sure. I can say that currently I have to move the viewPlane -2 meters because the normal is facing the "wrong" direction for my use case. That doesn't seem like a strong reason to prefer "into the screen" over the current "out of the screen" though. I mostly just prefer that Plane3d and SketchPlane3d have the same normal, and X/Y direction

*I picked 2 meters because the distance between the character and camera is 2 meters

**Comment by ianmackenzie** [comment]
Actually now that I take a closer look I think the current API is probably fine - there's currently `Viewpoint3d.viewPlane` that returns a sketch plane at the camera position with X and Y axes oriented the way you'd expect, and `Camera3d.clipPlane` that is offset forwards by the camera's clip depth and has the normal flipped so that visible objects have positive depth.

I think it's probably OK for those two to have 'opposite' orientations, since they're conceptually pretty different things (and have different origin points). So I think this issue can probably just be closed - thoughts?

**Comment by MartinSStewart** [comment]
Yeah, those two functions sound reasonable. If you're not changing the sketch plane to a Plane3d then that takes care of my concern anyway, so I think you can close this issue.
